apisearch:
  app_id: 'as-29be77d7-2f64-4522'
  index_id: 'eu1-15d067ec-b6d2-4a8a'
  token: 'eu1-bb44c262-49a5-495e-9a5f-0d4185ae0469'
  endpoint: 'https://eu1.apisearch.cloud'

cluster_url: https://apisearch.cloud
demo_form_url: https://www.apisearch.cloud/es/signup

languages: [es, ca, en]
root_language: es
pages: [index, terms_and_conditions, privacy_policy, prestashop]
assets: assets
files: [CNAME, robots.txt]
target: docs
